export enum SecurityType {
  'Aktie' = 'Aktie',
  'Inhaberaktie' = 'Inhaberaktie',
  'Namensaktie' = 'Namensaktie',
  'VinkulierteNamensaktie' = 'Vinkulierte Namensaktie',
  'Stammaktie' = 'Stammaktie / Stämme',
  'Vorzugsaktie' = 'Vorzugsaktie / Vorzüge',
  'InhaberVorzug' = 'Inhaber-Vorzugsaktien',
  'InhaberStamm' = 'Inhaber-Stammaktien',
  'InhaberGenuss' = 'Inhaber-Genußscheine O.N.',
  'BearerShares' = 'Bearer shares [Inhaberaktie]',
  'RegisteredShares' = 'Registered Shares [Namensaktie]',
  'RegisteredSharesA' = 'Registered Shares Type A [Namensaktie]',
  'AandelenAanToonder' = 'Aandelen aan toonder [Inhaberaktie]',
  'AandelenOopNaam' = 'Aandelen   oop naam [Namensaktie]',
  'ActionsAuPorteur' = 'Actions au Porteur [Inhaberaktie]',
  'ActionsNominatives' = 'Actions Nominatives [Namensaktie]',
  'Actions' = 'Actions [Aktie]',
  'ActionsPort' = 'Actions Port. (FR)',
  'ActionsNom' = 'Actions Nom. (FR)',
  'AccionesPort' = 'Acciones Port. (ES)',
  'AccionesNom' = 'Acciones Nom. (ES)',
  'AzioniNom' = 'Azioni nom. (IT)',
  'NamnAktierB' = 'Namn-Aktier B (SE)',
  'NavneAktierB' = 'Navne-Aktier B (DK)',
  'ETF' = 'ETF',
  'ADR' = 'ADR',
  'GovtBond' = 'Staatsanleihe',
  'CorpBond' = 'Unternehmensanleihe',
}

